### ISSUE TITLE
interpretation of uncertainty mass value for R-EDL

### ISSUE THREAD

**Issue by haruishi43** [MengyuanChen21/ICLR2024-REDL#1]
Thank you for your work.

This might be a simple question, but does introducing $\lambda$ change the scale of the uncertainty mass?

In the original EDL formulation (Sensoy2018), uncertainty mass is in the range of 0 and 1. This is because the uncertainty mass is expressed by $u = \frac{K}{S} = \frac{K}{\sum\alpha}$ where uncertainty is inversely proportional to the total evidence.

In your paper, you wrote that the uncertainty mass retains the same form, but I've noticed that when the $\lambda$ is lower than 1 (0.1 as in your experiments) the uncertainty mass's range is not guaranteed to be between 0 and 1 due to the fact that $\alpha = e + \lambda$. For example, when there are no evidence, the uncertainty mass will be $u = \frac{K}{\lambda K} > 1$.

I'm I understanding your paper correctly?

**Comment by MengyuanChen21** [comment]
Thank you for bringing this issue to my attention.

Introducing $\lambda$ does not change the scale of the uncertainty mass. Upon reviewing your comment, I realized that in the paper, just below Equation (9), I incorrectly stated that $u = C/S$. The accurate expression should indeed be $u = \lambda C/S$ to ensure that $u$ remains bounded between 0 and 1, and that $\sum b + u = 1$. This correction will not affect any other details of the paper.

I appreciate you pointing out this oversight. I will update the README file to clarify this correction.

**Comment by haruishi43** [comment]
Thank you for the prompt response!

$u = \lambda C / S$ does indeed satisfy the requirements.

I'm actually experimenting R-EDL on my dataset and I've noticed that the uncertainty mass value becomes significantly small for $\lambda=0.1$ when compared to $\lambda=1.0$ (this is after fixing the uncertainty mass equation). 
Empirically, around 0.5 was the sweet spot where the uncertainty mass is about right and have good accuracy.
