### ISSUE TITLE
The   "model_type": "genet" is not implemented

### ISSUE THREAD

**Issue by LinyeLi60** [MengyuanChen21/ICLR2024-REDL#3]
generating task from 0 to 10000
[14:29:02] * Starting Classification for 10000 Tasks...
  0%|                                                  | 0/1000 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "/home/lly/PythonProjects/REDL/code_fsl/main.py", line 309, in <module>
    main(proced_config_dict)
  File "/home/lly/PythonProjects/REDL/code_fsl/main.py", line 197, in main
    raise NotImplementedError
NotImplementedError

**Comment by LinyeLi60** [comment]
# ---- train classifier
            if model_type == 'evnet':
                classifier = train_iedl(support_data, support_label, loss_type, act_type, fisher_coeff,
                                        max_iter=lbfgs_iters, verbose=False, use_wandb=use_wandb, n_ep=ii)
            elif model_type == 'menet':
                classifier = train_medl(support_data, support_label, loss_type, act_type, lamb1, lamb2, fisher_coeff,
                                        max_iter=lbfgs_iters, verbose=False, use_wandb=use_wandb, n_ep=ii)
            else:
                raise NotImplementedError

**Comment by MengyuanChen21** [comment]
Sorry for the mistake. "genet" is the old name for "menet." Please replace all instances of "genet" with "menet." I have also corrected the configuration files.
